[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mkv2mp4ui"
version = "0.1.0"
authors = [
    {name = "Scott Peterman", email = "scottpeterman@gmail.com"},
]
description = "A Windows PyQt6 GUI application for batch converting MKV files to MP4"
readme = "README.md"
license = {text = "GPLv3"}
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Multimedia :: Video :: Conversion",
    "Topic :: Software Development :: User Interfaces",
    "Environment :: Win32 (MS Windows)",
]
keywords = [
    "mkv", "mp4", "video", "conversion", "ffmpeg", "gui", "pyqt6",
    "batch", "converter", "multimedia", "video-processing"
]
dependencies = [
    "PyQt6>=6.9.1",
    "ffmpeg-python>=0.2.0",
    "requests>=2.32.4",
    "certifi>=2025.6.15",
    "charset-normalizer>=3.4.2",
    "future>=1.0.0",
    "idna>=3.10",
    "urllib3>=2.4.0",
]

[project.urls]
Homepage = "https://github.com/scottpeterman/mkvtomp4ui"
Repository = "https://github.com/scottpeterman/mkvtomp4ui"
Issues = "https://github.com/scottpeterman/mkvtomp4ui/issues"
Documentation = "https://github.com/scottpeterman/mkvtomp4ui#readme"

[project.scripts]
mkv2mp4ui = "mkv2mp4ui.main:main"

[project.gui-scripts]
mkv2mp4ui-gui = "mkv2mp4ui.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["mkv2mp4ui*"]
exclude = ["tests*"]

[tool.setuptools.package-data]
"mkv2mp4ui" = ["*.py"]